const nutritional = [
  { Id: 0, nameEn: "Wartość energetyczna", value: 41, unit: 'kcal' },
  { Id: 1, nameEn: "Tłuszcz", value: 0.2, unit: "g" },
  { Id: 2, nameEn: "Kwasy tłuszczowe nasycone", value: 0, unit: "g" },
  { Id: 3, nameEn: "Kwasy tłuszczowe wielonienasycone", value: 0.1, unit: "g" },
  { Id: 4, nameEn: "Kwasy tłuszczowe jednonienasycone", value: 0, unit: "g" },
  { Id: 5, nameEn: "Kwasy tłuszczowe trans", value: 0, unit: "g" },
  { Id: 6, nameEn: "Cholesterol", value: 0, unit: "mg" },
  { Id: 7, nameEn: "Sód", value: 69, unit: "mg" },
  { Id: 8, nameEn: "Potas", value: 320, unit: "mg" },
  { Id: 9, nameEn: "Węglowodany", value: 10, unit: "g" },
  { Id: 10, nameEn: "Błonnik", value: 2.8, unit: "g" },
  { Id: 11, nameEn: "Cukry", value: 4.7, unit: "g" },
  { Id: 12, nameEn: "Białko", value: 0.9, unit: "g" },
  { Id: 13, nameEn: "Witamina A", value: 706, unit: "IU" },
  { Id: 14, nameEn: "Kwas askorbinowy", value: 5.9, unit: "mg" },
  { Id: 15, nameEn: "Wapń", value: 33, unit: "mg" },
  { Id: 16, nameEn: "Żelazo", value: 0.3, unit: "mg" },
  { Id: 17, nameEn: "Witamina D", value: 0, unit: "IU" },
  { Id: 18, nameEn: "Witamina B6", value: 0.1, unit: "mg" },
  { Id: 19, nameEn: "Witamina B12", value: 0, unit: "µg" },
  { Id: 20, nameEn: "Magnez", value: 12, unit: "mg" },
];

module.exports = nutritional;